import dotenv

ELASTICSEARCH_INDEX_0 = "ELASTICSEARCH_INDEX_SILVER"
ELASTICSEARCH_INDEX_1 = "ELASTICSEARCH_INDEX_GOLD"
ELASTICSEARCH_HOSTS = "ELASTICSEARCH_HOSTS"
KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"
KAFKA_TOPIC = "KAFKA_TOPIC"
SPARK_STORAGE_PATH = "SPARK_STORAGE_PATH"
SPARK_PROCESS_PATH = "SPARK_PROCESS_PATH"
SPARK_ANALYSIS_PATH = "SPARK_ANALYSIS_PATH"
SPARK_ELASTICSEARCH_CHECKPOINT = "SPARK_ELASTICSEARCH_CHECKPOINT"
DELTA_WORD_CLOUD_PATH = "DELTA_WORD_CLOUD_PATH"
ANALYZED_WORD_CLOUD_PATH_0 = "ANALYZED_WORD_CLOUD_PATH_0"
ANALYZED_WORD_CLOUD_PATH_1 = "ANALYZED_WORD_CLOUD_PATH_1"


class TestConfigLoader:
    @staticmethod
    def load_config(dotenv_filename=".env.test"):
        path = dotenv.find_dotenv(dotenv_filename)
        return dotenv.dotenv_values(dotenv_path=path)
